{{- if .Values.Consul.Backup.Enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-{{.Values.Consul.Backup.ComponentName}}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: {{.Values.Consul.Backup.ComponentName}}
    app: {{ template "name" . }}
spec:
  replicas: {{ .Values.Consul.Backup.Replicas }}
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        component: {{.Values.Consul.Backup.ComponentName}}
        app: {{ template "name" . }}
    spec:
      containers:
      - name: {{ template "fullname" . }}-{{.Values.Consul.Backup.ComponentName}}
        image: "{{.Values.Consul.Backup.Image}}:{{.Values.Consul.Backup.ImageTag}}"
        imagePullPolicy: {{.Values.Consul.Backup.ImagePullPolicy}}
        command:
          - "/bin/sh"
          - "-ce"
          - "sleep 999999999"
        env:
        - name: "CONSUL_ARGS"
          value: -rejoin -config-dir=/consul/config -config-dir=/consul/secrets -datacenter={{.Values.Consul.Datacenter}} -retry-join={{ template "fullname" . }}-{{.Values.Consul.ComponentName}}
        - name: "S3_URL"
          value: {{.Values.Consul.Backup.S3URL}}/{{ .Release.Name }}/
        {{- if .Values.Vault.AutoRestore }}
        lifecycle:
          postStart:
            exec:
              command:
                - "/bin/sh"
                - "-ec"
                - |
                  /init.sh {{ template "tls_skip_verify" . }}
        {{- end }}
        resources:
          limits:
            cpu: {{ .Values.Consul.Backup.Cpu }}
            memory: {{ .Values.Consul.Backup.Memory }}
          requests:
            cpu: {{ .Values.Consul.Backup.Cpu }}
            memory: {{ .Values.Consul.Backup.Memory }}
        volumeMounts:
        - name: consul-config
          mountPath: /consul/config
          readOnly: false
        - name: tls-consul
          mountPath: /consul/tls
          readOnly: true
        - name: ca-consul
          mountPath: /consul/ca
          readOnly: true
        - name: gossip-key
          mountPath: /consul/secrets
          readOnly: true
      volumes:
      - name: consul-config
        configMap:
          name: {{ template "fullname" . }}-{{.Values.Consul.Backup.ComponentName}}
          items:
          - key: config.json
            path: config.json
      - name: tls
        secret:
          secretName: {{ template "fullname" . }}.tls
      - name: ca-consul
        secret:
          secretName: {{ template "fullname" . }}-consul.ca
      - name: tls-consul
        secret:
          secretName: {{ template "fullname" . }}-consul.tls
      - name: gossip-key
        secret:
          secretName: {{ template "fullname" . }}-consul-gossip-json
{{- end }}
