{{- if and .Values.Vault.Tls.CertString .Values.Vault.Tls.KeyString }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}.tls
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: {{.Values.Vault.ComponentName}}
    app: {{ template "name" . }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.Vault.Tls.CertString | b64enc }}
  tls.key: {{ .Values.Vault.Tls.KeyString | b64enc }}
{{- end }}
