{{- if .Values.Vault.AutoUnseal }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-keys
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: unseal-keys
    app: {{ template "name" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "100"
type: Opaque
data:
  key1: {{ "foo" | b64enc }}
{{- end }}
